name: Website Bot

on:
  workflow_dispatch:
    inputs:
      website:
        description: 'URL of the website to visit'
        required: true
        default: 'https://example.com'

jobs:
  visit-website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Check Website
        run: |
          echo "Checking the website: ${{ github.event.inputs.website }}"
        env:
          WEBSITE_URL: ${{ github.event.inputs.website }}
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
